version: '3'
services:
  db:
    container_name: mysql-docker-container
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'senla-workhome-2'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3366:3306"
    expose:
      - '3306'
    volumes:
      - /rent-app-db:/var/lib/mysql
    networks:
      - rent-app-network
  rent-app:
    depends_on:
      - db
    container_name: rent-app
    build:
      context: ../.
      dockerfile: ./docker/rent-app/Dockerfile
    image: rent-app:latest
    ports:
      - "8088:8080"
    networks:
      - rent-app-network
networks:
  rent-app-network:
    driver: bridge