version: '2'
services:
  db_postgres:
    container_name: postgres-docker-container
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5444:5432"
    volumes:
      - /rent-app-db/postgresql:/var/lib/postgresql
    networks:
      - rent-app-network
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "ivan.aukhim@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - /home/user/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - rent-app-network
  config-server:
    container_name: config-server-container
    image: iaukhim/config-server:latest
    volumes:
      - /home/user/certificates/config-server:/certificates/
      - /home/user/certificates/github:/root/.ssh/
    ports:
      - "8888:8888"
    expose:
      - 8989
    networks:
      - rent-app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8989/actuator/health"]
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 10s
  rent-app:
    depends_on:
      config-server:
        condition: service_healthy
        restart: true
      db_postgres:
        condition: service_started
    container_name: rent-app
    image: iaukhim/rent-app:latest
    ports:
      - "8088:8080"
    networks:
      - rent-app-network
networks:
  rent-app-network:
    driver: bridge